name: Generate Channel Info

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create dist directory if it doesn't exist
        run: mkdir -p ./dist

      - name: Run generate_channel_info_updated.js script
        run: node generate_channel_info_updated.js

      - name: Move generated channel_info.txt to main directory
        run: mv ./dist/channel_info.txt ./channel_info.txt

      - name: Commit and push channel_info.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add channel_info.txt
          git commit -m "Update channel_info.txt"
          git push
