name: Generate Channel Info

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run generate_channel_info_updated.js script
        run: node generate_channel_info_updated.js

      - name: Commit and Push generated file to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status  # ตรวจสอบสถานะของไฟล์ที่ถูกติดตาม
          git add -f dist/channel_info.txt  # บังคับให้เพิ่มไฟล์แม้จะถูก .gitignore
          git commit -m "Update generated channel_info.txt"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

    post:
      - name: Post Set up Node.js environment
        run: echo "Node.js environment setup is complete"

      - name: Post Checkout repository content
        run: echo "Repository content checkout is complete"

      - name: Complete job
        run: echo "Job complete"
